---
network_configuration:
  default_enable_cis_checks: false
  default_freeform_tags:
    vision-environment: vision
  network_configuration_categories:
    demo:
      category_freeform_tags:
        vision-oci-aws-ipsec: demo
      non_vcn_specific_gateways:
        dynamic_routing_gateways:
          DRG-VISION-KEY:
            display_name: drg-vision
            drg_attachments:
              DRG-VCN-ATTACH-VISION-KEY:
                display_name: drg-vcn-attach-vision
                network_details:
                  attached_resource_key: VISION-GENERIC-FC-VCN-KEY
                  type: VCN
        fast_connect_virtual_circuits:
          VISON-FC-VC-1-KEY:
            bandwidth_shape_name: 1 Gbps
            cross_connect_mappings:
              MAPPING-1-KEY:
                customer_bgp_peering_ip: 192.168.3.1/30
                oracle_bgp_peering_ip: 192.168.3.2/30
            customer_asn: '65000'
            display_name: vision_fc_vc_01
            gateway_key: DRG-VISION-KEY
            provider_service_key: VISION-FC-VC-01-EQUINIX-FABRIC-KEY
            provision_fc_virtual_circuit: true
            show_available_fc_virtual_circuit_providers: false
            type: PRIVATE
      vcns:
        VISION-GENERIC-FC-VCN-KEY:
          block_nat_traffic: false
          cidr_blocks:
          - 172.16.0.0/24
          display_name: vision-generic-fc-vcn
          dns_label: visionvcn
          is_attach_drg: false
          is_create_igw: false
          is_ipv6enabled: false
          is_oracle_gua_allocation_enabled: false
          route_tables:
            RT-01-KEY:
              display_name: rt-01
              route_rules:
                drg_route:
                  description: Route for on-premises over IPSEC VPN
                  destination: 10.0.0.0/16
                  destination_type: CIDR_BLOCK
                  network_entity_key: DRG-VISION-KEY
          security_lists:
            SECLIST-01-KEY:
              display_name: prv-subnet
              egress_rules:
              - description: egress to 10.0.0.0/16 over all TCP ports
                dst: 10.0.0.0/16
                dst_type: CIDR_BLOCK
                protocol: TCP
                stateless: false
              ingress_rules:
              - description: ingress from 10.0.0.0/16 over TCP:22
                dst_port_max: 22
                dst_port_min: 22
                protocol: TCP
                src: 10.0.0.0/16
                src_type: CIDR_BLOCK
                stateless: false
              - description: ingress from 10.0.0.0/16 over ICMP:all
                protocol: ICMP
                src: 10.0.0.0/16
                src_type: CIDR_BLOCK
                stateless: false
          subnets:
            PRIVATE-REGIONAL-SUBNET-KEY:
              cidr_block: 172.16.0.0/24
              dhcp_options_key: default_dhcp_options
              display_name: private-regional-sub
              dns_label: prv
              ipv6cidr_blocks: []
              prohibit_internet_ingress: true
              prohibit_public_ip_on_vnic: true
              route_table_key: RT-01-KEY
              security_list_keys:
              - SECLIST-01-KEY